#
# Common code for all Loongson 1 based systems
#

obj-$(CONFIG_MACH_LOONGSON1) += common/

#
# Loongson LS1X board
#

obj-$(CONFIG_LOONGSON1_LS1A)  += ls1a/
obj-$(CONFIG_LOONGSON1_LS1B)  += ls1b/
obj-$(CONFIG_LOONGSON1_LS1C)  += ls1c/
