# Loongson1 Platform Support
snd-soc-ls1x-objs := ls1x-pcm.o
snd-soc-ls1x-i2s-objs := ls1x-i2s.o
snd-soc-ls1x-ac97-objs := ls1x-ac97.o

obj-$(CONFIG_SND_LS1X_SOC) += snd-soc-ls1x.o
obj-$(CONFIG_SND_LS1X_SOC_I2S) += snd-soc-ls1x-i2s.o
obj-$(CONFIG_SND_LS1X_SOC_AC97) += snd-soc-ls1x-ac97.o

# LS1X Machine Support
snd-ls1x-objs := ls1x.o

obj-$(CONFIG_SND_LS1X) += snd-ls1x.o

